include: package:lints/recommended.yaml

analyzer:
  exclude:
    - android/**
    - ios/**

linter:
  rules:
    - avoid_print
    - avoid_unnecessary_containers
    - avoid_unused_constructor_parameters
    - avoid_web_libraries_in_flutter
    - avoid_renaming_method_parameters
    - no_logic_in_create_state
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_single_quotes
    - prefer_final_locals
    - prefer_typing_uninitialized_variables
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_build_context_synchronously
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - unnecessary_new
    - lines_longer_than_80_chars